### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by josephlewis42** [heedy/pipescript#7]
This is the right place for adding in JavaScript transforms so we can use things like [geolib](https://www.npmjs.com/package/geolib) to solve #6.

I propose we use Duktape.

**Comment by dkumor** [comment]
That sounds reasonable.

What do you think of something like the following:

javascript.go
```go
// Registry of external scripts
ExternalScripts = map[string]ExternalScript

type ExternalScript struct {
Name,Description, etc

Generator: Function to call on initialization
Next: Function to call in next
}

// This would register the transform
func RegisterJavascriptTransforms(script string) error

```

As for javascript:

```javascript

function nextfunc(transformiterator) {
    datapoint = transformiterator.Next()
    // datapoint is a dictionary {"datapoint": {"t","d"}, "args": [{"t","d"} ...]}
}

function genfunc(name, args) {
   return {"args": args, "constant": false, "onetoone": true, etc}
}

pipescript.register("myfunction","mydescription",[{"arg1",etc}], genfunc, nextfunc)
```

This would be useful in standalone pipescript (transforms can be defined in js files that are loaded).

It can also be useful for ConnectorDB, which can a) load all js files from a special directory, and b) have a special loadjs rest api call (which is obviously limited to admin/whomever has necessary permissions)

**Comment by dkumor** [comment]
I suggest putting this in a 'javascript' subdirectory

**Comment by dkumor** [comment]
BTW: I made many changes in the underlying structure of PipeScript, so if you decide to do it, make sure to read the wiki before jumping in: https://github.com/connectordb/pipescript/wiki

**Comment by dkumor** [comment]
maybe someday, but not a priority now.
